/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JFrame;


/**
 *
 * @author HIRO
 */
public class MainFrame extends javax.swing.JFrame {

    AttendancePanel attendance;
    StatusPanel status;
    TimeTablePanel timetable;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.BasePanel.setVisible(false);
        
        this.timetable = new TimeTablePanel(this);
        this.add(this.timetable);
        this.revalidate();
        this.repaint();
        this.timetable.setVisible(true);

        this.attendance = null;
//        this.add(this.attendance);

        this.status = null;
//        this.add(this.status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BasePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout BasePanelLayout = new javax.swing.GroupLayout(BasePanel);
        BasePanel.setLayout(BasePanelLayout);
        BasePanelLayout.setHorizontalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        BasePanelLayout.setVerticalGroup(
            BasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
          MainFrame frame = new MainFrame();
          frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
          frame.pack();
          frame.setTitle("AttendanceCheck");
          frame.setBounds(150, 50, 1280, 770);
          frame.setVisible(true);
        });
    }

    /**
     * 座席画面へ切り替え
     * @param lessonID 授業番号
     */
    public void createAttendance(String lessonID, subjectDialog dialog){
        this.timetable.setVisible(false);
        dialog.setVisible(false);
        dialog = null;
        this.attendance = new AttendancePanel(this, lessonID);
        this.add(this.attendance);
        this.attendance.setVisible(true);
    }

    /**
     * 欠課表示画面へ切り替え
     * @param lessonID 授業番号
     * @param studentID 名列番号
     * @param dialog
     */
    public void createStatus(String lessonID, int studentID, subjectDialog dialog){
        this.timetable.setVisible(false);
        dialog.setVisible(false);
        dialog = null;
        this.status = new StatusPanel(this, lessonID, studentID);
        this.add(this.status);
        this.status.setVisible(true);
    }

    /**
     * トップへ戻る
     */
    public void returnTimeTable(){
        this.timetable.setVisible(true);
        if(this.attendance != null){
            this.attendance.setVisible(false);
            this.remove(this.attendance);
        }
        if(this.status != null) {
            this.status.setVisible(false);
            this.remove(this.status);
        }
        this.status = null;
        this.attendance = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePanel;
    // End of variables declaration//GEN-END:variables
}
